# Generated by Django 3.0.5 on 2021-08-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lattice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length_a', models.FloatField()),
                ('length_b', models.FloatField()),
                ('length_c', models.FloatField()),
                ('angle_a', models.FloatField()),
                ('angle_b', models.FloatField()),
                ('angle_c', models.FloatField()),
                ('image', models.CharField(max_length=2500)),
            ],
        ),
    ]
