# Generated by Django 3.0.5 on 2021-08-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lattice', '0005_filemodel_userfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
